//HEADER_EXPORT_MEL
startAttrPreset("substance"); 
blendAttr "dyn_Diffuse_Sharpen" 0;
blendAttr "dyn_Normal_Strength" 3.662;
blendAttr "dyn_Normal_Fine_Smoothing" 1;
blendAttr "dyn_Normal_Soften" 0.383;
blendAttr "dyn_Normal_Large_Smoothing" 0.485;
blendAttr "dyn_Normal_Medium_Smoothing" 1;
blendAttr "dyn_Specular_Sharpen" 0;
blendAttr "dyn_Diffuse_Neutralize" 1;
blendAttr "dyn_Normal_Shape_Recognition" 0;
endAttrPreset();
